# Generated by Django 3.2.6 on 2021-09-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_studentbulkupload_csv_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='')),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='csvmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeName', models.CharField(max_length=50)),
                ('JobTitle', models.CharField(max_length=50)),
                ('BasePay', models.FloatField()),
                ('OvertimePay', models.FloatField()),
                ('Agency', models.CharField(max_length=100)),
            ],
        ),
    ]
