# Generated by Django 3.2.6 on 2021-09-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_csv_csvmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='csv',
            new_name='csvfile',
        ),
    ]
